# stages:
#     - build
#     - test

# before_script:

linbuild:
    stage: build
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make
    artifacts:
        paths:
            - libacktrack.so
            - cdemo/cdemo

lintest:
    stage: test
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make citest

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  - cp libacktrack.so public/
  artifacts:
    paths:
    - public
  only:
  - master

# winbuild:
#     stage: build
#     tags:
#         - windows
#     script:
#         - Find-PackageProvider -Name 'Nuget' -ForceBootstrap -IncludeDependencies
#         - Install-Module -Name Invoke-MsBuild -RequiredVersion 2.6.0 -Force
#         - Import-Module Invoke-MsBuild
#         - Invoke-MsBuild -Path "acktrack.sln" -BypassVisualStudioDeveloperCommandPrompt
