# stages:
#     - build
#     - test

# before_script:

linbuild:
    stage: build
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make
    artifacts:
        paths:
            - libacktrack.so
            - cdemo/cdemo

lintest:
    stage: test
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make citest

winbuild:
    stage: build
    tags:
        - windows
    script:
        - '$msbuild = "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe"'
        - '& $msbuild'
        # - dir -path c:\ -recurse > filesystem.txt
        # - '$vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"'
        # - '& $vswhere'
        # - '$msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1'
        # - 'echo Running msbuild from $msbuild'
        # - '& $msbuild'
    artifacts:
        paths:
            - Debug/

#wintest:
#    stage: test
#    tags:
#        - windows
#    script:
        # not possible due to npcap licensing???
        # - choco install npcap
        - Debug/cdemo google.com 80

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  - cp Debug/libacktrack.so public/
  - cp acktrack.dll public/
  artifacts:
    paths:
    - public
  only:
  - master
