# stages:
#     - build
#     - test

# before_script:

linbuild:
    stage: build
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make
    artifacts:
        paths:
            - libacktrack.so
            - cdemo/cdemo

lintest:
    stage: test
    needs: ["linbuild"]
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make citest

winbuild:
    stage: build
    tags:
        - windows
    script:
        - '$msbuild = "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe"'
        - '& $msbuild'
        # - dir -path c:\ -recurse > filesystem.txt
        # - '$vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"'
        # - '& $vswhere'
        # - '$msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1'
        # - 'echo Running msbuild from $msbuild'
        # - '& $msbuild'
    artifacts:
        paths:
            - Debug/

## wintest:
##     stage: test
##     tags:
##         - windows
##     script:
##         - get-psdrive
##         - choco upgrade chocolatey
## #        - (choco install nmap -y --verbose --debug --trace) -and (echo success)
##         - (choco install nmap -y) -or (echo success)
##         - echo nmap installation complete
##         - copy C:\windows\system32\npcap\wpcap.dll Debug\
##         - Debug\cdemo "google.com" "80"
##     after_script:
##         - echo $? $LASTEXITCODE
##         - echo "Here's the log file ..."
##         - type C:\ProgramData\chocolatey\logs\chocolatey.log

#wintest:
#   stage: test
#   tags: 
#        - windows
#   script:
#       - choco install autoit
#       - Import-Module c:\Program Files (x86)\AutoIt3\AutoItX\AutoItX.psd1
#       (see https://www.autoitconsulting.com/site/scripting/autoit-cmdlets-for-windows-powershell/)
# what a pain in the ass

# not possible due to npcap licensing???
#wintest:
#    stage: test
#    tags:
#        - windows
#    script:
        # - choco install npcap
#        - Debug/cdemo google.com 80

pages:
  stage: deploy
  script:
  - cp libacktrack.so public/
  - cp Debug/acktrack.dll public/
  - 'echo "document.write(\"`git log -1 --pretty=\"%h (%ad): %B\"`\");" > public/lastupdate.js'
  artifacts:
    paths:
    - public
  only:
  - master
