stages:
    - build
    - test

before_script:
    - apt-get update -qq && apt-get install -y -qq libpcap-dev

linbuild:
    stage: build
    script:
        - make
    artifacts:
        paths:
            - libacktrack.so
            - cdemo/cdemo

winbuild:
    stage: build
    tags:
        - windows
    script:
        - Find-PackageProvider -Name 'Nuget' -ForceBootstrap -IncludeDependencies
        - Install-Module -Name Invoke-MsBuild -RequiredVersion 2.6.0 -Force
        - Import-Module Invoke-MsBuild
        - Invoke-MsBuild -Path "acktrack.sln"

lintest:
    stage: test
    script:
        - make citest
