# stages:
#     - build
#     - test

# before_script:

linbuild:
    stage: build
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make
    artifacts:
        paths:
            - libacktrack.so
            - cdemo/cdemo

lintest:
    stage: test
    script:
        - apt-get update -qq && apt-get install -y -qq libpcap-dev
        - make citest

winbuild:
    stage: build
    tags:
        - windows
    script:
        - '$vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"'
        - '& $vswhere'
        - '$msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1'
        - 'echo Running msbuild from $msbuild'
        - '& $msbuild'


pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  - cp libacktrack.so public/
  artifacts:
    paths:
    - public
  only:
  - master
